USE DATABASE EXCHANGE_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE EXCHANGE_RAW(
    RATE_TIME TIMESTAMP,
    BASE_CURRENCY STRING,
    TARGET_CURRENCY STRING,
    EXCHANGE_RATE FLOAT
);

USE SCHEMA STAGING;

CREATE OR REPLACE TABLE STG_EXCHANGE(
    RATE_TIME TIMESTAMP,
    BASE_CURRENCY STRING,
    TARGET_CURRENCY STRING,
    EXCHANGE_RATE FLOAT
);

USE SCHEMA MART;

CREATE OR REPLACE TABLE MART_EXCHANGE(
    RATE_DATE DATE,
    TARGET_CURRENCY STRING,
    AVG_RATE FLOAT,
    MAX_RATE FLOAT,
    MIN_RATE FLOAT,
    RECORD_COUNT INTEGER
);