USE DATABASE EXCHANGE_DB;
USE SCHEMA STAGING;

CREATE OR REPLACE TASK TASK_RAW_TO_STAGING
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 5 * * * * Asia/Tokyo'
AS
INSERT INTO STG_EXCHANGE
SELECT
    RATE_TIME,
    BASE_CURRENCY,
    TARGET_CURRENCY,
    EXCHANGE_RATE
FROM EXCHANGE_DB.RAW.EXCHANGE_STREAM;


CREATE OR REPLACE TASK TASK_STAGING_TO_MART
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 10 * * * * Asia/Tokyo'
AS
CREATE OR REPLACE TABLE EXCHANGE_DB.MART.MART_EXCHANGE AS
SELECT
    DATE(RATE_TIME) AS RATE_DATE,
    TARGET_CURRENCY,
    AVG(EXCHANGE_RATE) AS AVG_RATE,
    MAX(EXCHANGE_RATE) AS MAX_RATE,
    MIN(EXCHANGE_RATE) AS MIN_RATE,
    COUNT(*) AS RECORD_COUNT
FROM EXCHANGE_DB.STAGING.STG_EXCHANGE
GROUP BY DATE(RATE_TIME), TARGET_CURRENCY;